title: "Talent Consulting Blog"
description: "Insights on digital transformation and modern delivery"
url: "https://talentconsulting.uk"
baseurl: ""
author: "Talent Consulting"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
paginate: 5
paginate_path: "/page:num"